download.file(url = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile = "household_power_consumption.zip", method = "curl")
unzip("household_power_consumption.zip")
b <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", as.is = TRUE, na.strings = "?")
c <- b[as.Date(b$Date, format = "%d/%m/%Y")==as.Date("01/02/2007", format = "%d/%m/%Y")|as.Date(b$Date, format = "%d/%m/%Y")==as.Date("02/02/2007", format = "%d/%m/%Y"),]
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
with (c, {
  plot(as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"), Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
  plot(as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"), Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
  plot(as.POSIXct(paste(c$Date, c$Time), format = "%d/%m/%Y %H:%M:%S"), c$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
  legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n")
  points(as.POSIXct(paste(c$Date, c$Time), format = "%d/%m/%Y %H:%M:%S"), c$Sub_metering_2, type = "l", col = "red")
  points(as.POSIXct(paste(c$Date, c$Time), format = "%d/%m/%Y %H:%M:%S"), c$Sub_metering_3, type = "l", col = "blue")
  plot(as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"), Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
})
dev.off()